version: '3'

services:
   solr:
      image: solr:6.6.0@sha256:e8f279c9ab594525ab0344c0cb44d5f2a2e308bec3e14a11648095af15cad90b
      container_name: solr
      volumes:
        - ./solr/managed-schema:/opt/solr/server/solr/configsets/basic_configs/conf/managed-schema:ro
        - ./solr/solrconfig.xml:/opt/solr/server/solr/configsets/basic_configs/conf/solrconfig:ro
      command: solr-create -c nutch
      ports:
         - 8983:8983

   nutch:
      image: apache/nutch:release-1.13@sha256:270a933f2311f7f8b4d477139d72fcb95eec284903642c6515c279aafaa09e66
      container_name: nutch
      environment:
        JAVA_HOME: /usr/lib/jvm/java-7-oracle/jre/
      volumes:
        - ./nutch/nutch-site.xml:/root/nutch/conf/nutch-site.xml:ro
        - ./nutch/regex-urlfilter.txt:/root/nutch/conf/regex-urlfilter.txt:ro
        - ./nutch/seed.txt:/root/nutch/urls/seed.txt:ro
      #IMPORTANTE: Existen dos modos de ejecución: `interactivo` (tty) o `servicio` (command). Mantener uno de los dos comentado
      tty: true
      # command: /root/nutch/bin/crawl -i -D solr.server.url=http://solr:8983/solr/nutch /root/nutch/urls/seed.txt TestCrawl 2 #Ejecuta el crawling automáticamente
      depends_on:
         - solr
